// =============================================================================
// Temperature Grid Lookup — SST (water) and air temperature
// =============================================================================
//
// Loads lightweight JSON grids (2° resolution) and bilinearly interpolates
// to get temperature at any lat/lng. Grids are generated by Python scripts
// and served as static files from public/data/.

export interface TempGrid {
  lat_start: number;
  lat_step: number; // negative (north→south)
  lng_start: number;
  lng_step: number;
  rows: number;
  cols: number;
  data: number[][]; // [row][col], -999 = no data
}

// ---------------------------------------------------------------------------
// Grid cache (loaded once per session)
// ---------------------------------------------------------------------------

let sstGrid: TempGrid | null = null;
let sstLoadPromise: Promise<TempGrid | null> | null = null;

let airGrid: TempGrid | null = null;
let airLoadPromise: Promise<TempGrid | null> | null = null;

async function loadGrid(url: string): Promise<TempGrid | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return (await res.json()) as TempGrid;
  } catch {
    return null;
  }
}

async function getSST(): Promise<TempGrid | null> {
  if (sstGrid) return sstGrid;
  if (!sstLoadPromise) {
    sstLoadPromise = loadGrid('/data/water-temp-grid.json').then((g) => {
      sstGrid = g;
      sstLoadPromise = null;
      return g;
    });
  }
  return sstLoadPromise;
}

async function getAirTemp(): Promise<TempGrid | null> {
  if (airGrid) return airGrid;
  if (!airLoadPromise) {
    airLoadPromise = loadGrid('/data/air-temp-grid.json').then((g) => {
      airGrid = g;
      airLoadPromise = null;
      return g;
    });
  }
  return airLoadPromise;
}

// ---------------------------------------------------------------------------
// Bilinear interpolation on a grid
// ---------------------------------------------------------------------------

function sampleGrid(grid: TempGrid, lat: number, lng: number): number | null {
  // Convert lat/lng to fractional row/col indices
  const row = (lat - grid.lat_start) / grid.lat_step;
  const col = (lng - grid.lng_start) / grid.lng_step;

  // Bounds check
  if (row < 0 || row >= grid.rows - 1 || col < 0 || col >= grid.cols - 1) {
    return null;
  }

  const r0 = Math.floor(row);
  const c0 = Math.floor(col);
  const fr = row - r0;
  const fc = col - c0;

  // Get 4 surrounding values
  const v00 = grid.data[r0][c0];
  const v01 = grid.data[r0][c0 + 1];
  const v10 = grid.data[r0 + 1][c0];
  const v11 = grid.data[r0 + 1][c0 + 1];

  // Skip if any neighbor is no-data
  if (v00 === -999 || v01 === -999 || v10 === -999 || v11 === -999) {
    // Fall back to nearest valid value
    const nearest = [v00, v01, v10, v11].filter((v) => v !== -999);
    return nearest.length > 0 ? nearest[0] : null;
  }

  // Bilinear interpolation
  return (
    v00 * (1 - fr) * (1 - fc) +
    v01 * (1 - fr) * fc +
    v10 * fr * (1 - fc) +
    v11 * fr * fc
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get water temperature (SST) at a point in °C. Returns null if unavailable.
 */
export async function getWaterTempAtPoint(
  lat: number,
  lng: number
): Promise<number | null> {
  const grid = await getSST();
  if (!grid) return null;
  return sampleGrid(grid, lat, lng);
}

/**
 * Get air temperature at a point in °C. Returns null if unavailable.
 */
export async function getAirTempAtPoint(
  lat: number,
  lng: number
): Promise<number | null> {
  const grid = await getAirTemp();
  if (!grid) return null;
  return sampleGrid(grid, lat, lng);
}
