#!/usr/bin/env python3
"""
Convert WaveWatch III GRIB2 data to GeoJSON format.

Processes all forecast hours in data/grib/ directory.

Input:  data/grib/gfswave.*.global.0p25.f*.grib2
Output: public/data/wave-data-f000.geojson
        public/data/wave-data-f024.geojson
        ... etc
        public/data/wave-data.geojson (copy of f000 for backward compatibility)
"""

import glob
import json
import math
import os
import re
import shutil
import sys
from datetime import datetime

import cfgrib
import numpy as np
from PIL import Image
from scipy.ndimage import map_coordinates, uniform_filter

# Configuration
GRIB_DIR = "data/grib"
OUTPUT_DIR = "public/data"
SAMPLE_STEP = 24  # Every 6° (grid is 0.25°, so 6/0.25 = 24)
MIN_SWELL_HEIGHT = 0.1  # Minimum swell height to include

# PNG raster configuration
PNG_WIDTH = 1440
PNG_HEIGHT = 1440  # Square for Web Mercator projection
LUT_SIZE = 1024

# Water mask (generated by scripts/generate-water-mask.py)
WATER_MASK_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               'water_mask_1440x1440.png')
_water_mask = None


def get_water_mask():
    """Load the water mask (lazy, cached). Returns float array 0.0=land, 1.0=water."""
    global _water_mask
    if _water_mask is None:
        if os.path.exists(WATER_MASK_PATH):
            _water_mask = np.array(Image.open(WATER_MASK_PATH)).astype(np.float32) / 255.0
        else:
            print(f"Warning: Water mask not found at {WATER_MASK_PATH}, using full alpha")
            _water_mask = np.ones((PNG_HEIGHT, PNG_WIDTH), dtype=np.float32)
    return _water_mask

# Web Mercator limits (standard for web maps)
MAX_LATITUDE = 85.051129  # degrees — Mercator undefined at poles

# Color ramps: list of (normalized_position, R, G, B, A)
# Wave height: 0-15m, warm gray → light blue → deep navy
WAVE_HEIGHT_COLORS = [
    (0.0,   180, 175, 168, 120),   # warm muted gray (flat/negligible)
    (0.03,  150, 170, 200, 170),   # light steel blue (~0.5m)
    (0.10,  110, 155, 210, 200),   # clear light blue (~1.5m)
    (0.20,   70, 130, 200, 215),   # medium blue (~3m)
    (0.35,   50, 100, 180, 225),   # strong blue (~5m)
    (0.55,   35,  75, 160, 235),   # deep blue (~8m)
    (0.75,   25,  55, 130, 240),   # dark navy (~11m)
    (1.0,    15,  35, 100, 245),   # very dark navy (15m)
]
WAVE_HEIGHT_MIN = 0.0
WAVE_HEIGHT_MAX = 15.0

# Wave period: 0-25s, warm gray → lavender → deep indigo-purple
WAVE_PERIOD_COLORS = [
    (0.0,  180, 175, 168, 140),   # warm muted gray (short period)
    (0.1,  165, 160, 180, 160),   # purple-ish gray
    (0.25, 150, 140, 195, 180),   # light lavender
    (0.5,  120, 100, 180, 200),   # medium purple
    (0.75,  95,  65, 165, 220),   # stronger purple
    (1.0,   65,  40, 140, 235),   # deep indigo-purple
]
WAVE_PERIOD_MIN = 0.0
WAVE_PERIOD_MAX = 25.0

# Wind speed: 0-30 m/s, warm gray → teal → deep teal
WIND_SPEED_COLORS = [
    (0.0,  180, 175, 168, 140),   # warm muted gray (calm)
    (0.1,  160, 175, 172, 160),   # teal-ish gray
    (0.25, 120, 175, 170, 180),   # light teal
    (0.5,   60, 155, 150, 200),   # medium teal
    (0.75,  30, 130, 125, 220),   # stronger teal
    (1.0,   15, 100, 100, 235),   # deep teal
]
WIND_SPEED_MIN = 0.0
WIND_SPEED_MAX = 30.0


def round1(val):
    """Round to 1 decimal place, handling NaN."""
    if np.isnan(val):
        return None
    return round(float(val), 1)


def convert_longitude(lon):
    """Convert longitude from 0-360 to -180 to 180."""
    if lon > 180:
        return lon - 360
    return lon


def extract_forecast_hour(filename):
    """Extract forecast hour from filename like gfswave.t18z.global.0p25.f024.grib2"""
    match = re.search(r'\.f(\d{3})\.grib2$', filename)
    if match:
        return int(match.group(1))
    return None


def build_color_lut(color_ramp, lut_size=LUT_SIZE):
    """Pre-build a (lut_size, 4) uint8 lookup table from color stops."""
    lut = np.zeros((lut_size, 4), dtype=np.uint8)
    for i in range(len(color_ramp) - 1):
        pos0, r0, g0, b0, a0 = color_ramp[i]
        pos1, r1, g1, b1, a1 = color_ramp[i + 1]
        idx0 = int(pos0 * (lut_size - 1))
        idx1 = int(pos1 * (lut_size - 1))
        n = idx1 - idx0
        if n <= 0:
            continue
        t = np.linspace(0, 1, n, endpoint=False).reshape(-1, 1)
        seg = (1 - t) * np.array([r0, g0, b0, a0]) + t * np.array([r1, g1, b1, a1])
        lut[idx0:idx1] = seg.astype(np.uint8)
    # Fill last entry
    lut[-1] = np.array(color_ramp[-1][1:], dtype=np.uint8)
    return lut


# Pre-build LUTs at module load
WAVE_HEIGHT_LUT = build_color_lut(WAVE_HEIGHT_COLORS)
WAVE_PERIOD_LUT = build_color_lut(WAVE_PERIOD_COLORS)
WIND_SPEED_LUT = build_color_lut(WIND_SPEED_COLORS)


def apply_color_lut(grid, lut, min_val, max_val):
    """Map a 2D float grid to an RGBA image using a prebuilt LUT."""
    nan_mask = np.isnan(grid)
    # Normalize to [0, 1]
    normalized = np.clip((grid - min_val) / (max_val - min_val), 0, 1)
    normalized[nan_mask] = 0
    # Map to LUT indices
    indices = (normalized * (len(lut) - 1)).astype(np.int32)
    # Look up colors
    rgba = lut[indices]
    # NaN values become transparent (base map shows through)
    rgba[nan_mask] = [0, 0, 0, 0]

    return rgba


def fill_all_gaps(data_grid, iterations=50, fallback_value=0.3):
    """Fill ALL missing/zero/NaN pixels by iteratively expanding from valid data.

    Fills everywhere — including over land — since the frontend handles
    masking via MapLibre vector layers. After iterative expansion, any
    remaining unfilled pixels get fallback_value so no gray spots appear.

    data_grid:      2D float array (e.g. wave height on the Mercator pixel grid)
    iterations:     number of dilation passes (~1 pixel per pass)
    fallback_value: value for pixels that can't be reached by expansion
    """
    filled = data_grid.copy()

    for _ in range(iterations):
        missing = (filled == 0) | np.isnan(filled)
        if not missing.any():
            break

        valid = ~missing

        # Sum of valid neighbor values (3x3 kernel)
        neighbor_sum = uniform_filter(
            np.where(valid, filled, 0), size=3, mode='constant', cval=0
        )
        # Count of valid neighbors
        neighbor_count = uniform_filter(
            valid.astype(np.float64), size=3, mode='constant', cval=0
        )

        # Average where we have at least one valid neighbor
        with np.errstate(divide='ignore', invalid='ignore'):
            neighbor_avg = np.where(
                neighbor_count > 0, neighbor_sum / neighbor_count, 0
            )

        fill_mask = missing & (neighbor_count > 0)
        filled[fill_mask] = neighbor_avg[fill_mask]

    # Fill any remaining gaps with fallback value (deep interior of continents)
    remaining = (filled == 0) | np.isnan(filled)
    if remaining.any():
        filled[remaining] = fallback_value

    return filled


def reproject_to_mercator(equirect_array, output_height=PNG_HEIGHT, output_width=PNG_WIDTH):
    """Vectorized reprojection from equirectangular to Web Mercator.

    Input: equirect_array with shape (lat, lon) where lat goes from +90 (top)
           to -90 (bottom) and lon goes from -180 (left) to +180 (right).
    Output: Mercator array with shape (output_height, output_width), clipped
            to ±MAX_LATITUDE.
    """
    in_height, in_width = equirect_array.shape

    # Create output coordinate grids
    out_y = np.arange(output_height)
    out_x = np.arange(output_width)
    out_xx, out_yy = np.meshgrid(out_x, out_y)

    # Convert output y to latitude via inverse Mercator
    y_norm = out_yy / (output_height - 1)  # 0 (top/north) to 1 (bottom/south)
    y_max = math.log(math.tan(math.pi / 4 + math.radians(MAX_LATITUDE) / 2))
    y_merc = y_max - y_norm * (2 * y_max)
    lat = np.degrees(2 * np.arctan(np.exp(y_merc)) - np.pi / 2)

    # Convert latitude to input row indices (input: +90 at row 0, -90 at last row)
    in_yy = (90 - lat) / 180 * (in_height - 1)

    # Longitude is linear in both projections
    in_xx = out_xx / (output_width - 1) * (in_width - 1)

    # Use scipy map_coordinates for bilinear interpolation
    # NaN handling: replace NaN with 0 for interpolation, then restore
    nan_mask = np.isnan(equirect_array)
    safe_array = equirect_array.copy()
    safe_array[nan_mask] = 0

    coords = np.array([in_yy, in_xx])
    output = map_coordinates(safe_array, coords, order=1, mode='constant', cval=0)

    # Build a NaN mask in the output: interpolate the mask to detect NaN regions
    nan_float = nan_mask.astype(np.float32)
    nan_interp = map_coordinates(nan_float, coords, order=1, mode='constant', cval=1)
    output[nan_interp > 0.5] = np.nan

    return output


def generate_raster_pngs(swh, primary_period, ws, forecast_hour, output_dir):
    """Generate 3 PNG rasters (wave height, period, wind) from full-res GRIB grids.

    Input grids are 721x1440 (0.25° global, 0-360 lon).
    Output PNGs are 1440x1440 Web Mercator (±85.05° lat, -180 to 180 lon).
    Data covers the entire globe — frontend handles land masking via vector layers.
    """
    UNIFORM_ALPHA = 210  # Semi-transparent so base map ocean color blends through

    layers = [
        ("wave-height", swh, WAVE_HEIGHT_LUT, WAVE_HEIGHT_MIN, WAVE_HEIGHT_MAX, 0.3),
        ("wave-period", primary_period, WAVE_PERIOD_LUT, WAVE_PERIOD_MIN, WAVE_PERIOD_MAX, 5.0),
        ("wind-speed", ws, WIND_SPEED_LUT, WIND_SPEED_MIN, WIND_SPEED_MAX, 2.0),
    ]

    for name, data, lut, vmin, vmax, fallback in layers:
        # Shift longitude from 0-360 to -180-180
        shifted = np.roll(data, -data.shape[1] // 2, axis=1)
        # Reproject from equirectangular to Web Mercator
        mercator = reproject_to_mercator(shifted)
        # Fill ALL gaps (ocean + land) so every pixel has data
        mercator = fill_all_gaps(mercator, fallback_value=fallback)
        # Apply color LUT
        rgba = apply_color_lut(mercator, lut, vmin, vmax)
        # Apply water mask: land pixels become transparent, water gets UNIFORM_ALPHA
        water_mask = get_water_mask()
        rgba[:, :, 3] = (water_mask * UNIFORM_ALPHA).astype(np.uint8)
        # Save PNG
        img = Image.fromarray(rgba, 'RGBA')
        png_path = os.path.join(output_dir, f"{name}-f{forecast_hour:03d}.png")
        img.save(png_path, 'PNG', optimize=True)


def load_gfs_air_temp(grib_path):
    """Try to load GFS 2m air temperature from a companion GRIB file.
    Returns a 2D array (lat x lon) in °C, or None if unavailable."""
    if not os.path.exists(grib_path):
        return None
    try:
        datasets = cfgrib.open_datasets(grib_path)
        for ds in datasets:
            for var_name in ['t2m', 't']:
                if var_name in ds.data_vars:
                    temp_k = ds[var_name].values
                    return temp_k - 273.15  # Kelvin → Celsius
        return None
    except Exception:
        return None


def download_gfs_temp_for_hour(run_date, run_cycle, forecast_hour, output_dir):
    """Download filtered GFS 2m temperature GRIB for a specific forecast hour.
    Uses NOMADS filter API to get just TMP at 2m (~500KB per file)."""
    import urllib.request

    fhour_str = f"{forecast_hour:03d}"
    output_path = os.path.join(output_dir, f"gfs-tmp2m-f{fhour_str}.grib2")

    if os.path.exists(output_path) and os.path.getsize(output_path) > 500:
        return output_path

    url = (
        f"https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?"
        f"dir=%2Fgfs.{run_date}%2F{run_cycle}%2Fatmos"
        f"&file=gfs.t{run_cycle}z.pgrb2.0p25.f{fhour_str}"
        f"&var_TMP=on&lev_2_m_above_ground=on"
    )

    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=30) as response:
            with open(output_path, 'wb') as f:
                f.write(response.read())
        return output_path
    except Exception:
        return None


def convert_grib_file(grib_path, output_path, file_num, total_files, air_temp_grid=None):
    """Convert a single GRIB file to GeoJSON."""
    filename = os.path.basename(grib_path)
    forecast_hour = extract_forecast_hour(filename)

    print(f"Processing f{forecast_hour:03d} ({file_num}/{total_files})...")

    # Load datasets
    datasets = cfgrib.open_datasets(grib_path)

    # Dataset 0: swell partitions (swdir, shts, mpts)
    # Dataset 1: main wave data (swh, ws, wdir)
    ds_swell = datasets[0]
    ds_wave = datasets[1]

    # Extract timestamps
    reference_time = str(ds_wave.time.values)[:19] + "Z"
    valid_time = str(ds_wave.valid_time.values)[:19] + "Z"

    # Get coordinate arrays
    lats = ds_wave.latitude.values
    lons = ds_wave.longitude.values

    # Get data arrays
    swh = ds_wave.swh.values
    ws = ds_wave.ws.values
    wdir = ds_wave.wdir.values
    shww = ds_wave.shww.values
    mpww = ds_wave.mpww.values
    wvdir = ds_wave.wvdir.values
    perpw = ds_wave.perpw.values

    # Swell partition data
    swdir = ds_swell.swdir.values
    shts = ds_swell.shts.values
    mpts = ds_swell.mpts.values

    # Generate PNG rasters from full-resolution grids
    generate_raster_pngs(swh, perpw, ws, forecast_hour, OUTPUT_DIR)

    features = []
    skipped_land = 0

    # Sample grid at 6° intervals
    for lat_idx in range(0, len(lats), SAMPLE_STEP):
        for lon_idx in range(0, len(lons), SAMPLE_STEP):
            lat = float(lats[lat_idx])
            lon = convert_longitude(float(lons[lon_idx]))

            wave_height = swh[lat_idx, lon_idx]

            # Skip land (NaN values)
            if np.isnan(wave_height):
                skipped_land += 1
                continue

            # Build swells array from partitions
            swells = []
            for p in range(3):
                height = shts[p, lat_idx, lon_idx]
                period = mpts[p, lat_idx, lon_idx]
                direction = swdir[p, lat_idx, lon_idx]

                if np.isnan(height) or height < MIN_SWELL_HEIGHT:
                    continue

                swells.append({
                    "height": round1(height),
                    "period": round1(period),
                    "direction": int(direction) if not np.isnan(direction) else 0
                })

            # Wind data
            wind = {
                "speed": round1(ws[lat_idx, lon_idx]) if not np.isnan(ws[lat_idx, lon_idx]) else 0,
                "direction": int(wdir[lat_idx, lon_idx]) if not np.isnan(wdir[lat_idx, lon_idx]) else 0
            }

            # Wind wave data
            ww_height = shww[lat_idx, lon_idx]
            wind_waves = None
            if not np.isnan(ww_height) and ww_height > 0:
                wind_waves = {
                    "height": round1(ww_height),
                    "period": round1(mpww[lat_idx, lon_idx]) if not np.isnan(mpww[lat_idx, lon_idx]) else None,
                    "direction": int(wvdir[lat_idx, lon_idx]) if not np.isnan(wvdir[lat_idx, lon_idx]) else None
                }

            # Air temperature at this grid point (from GFS, if available)
            air_temp = None
            if air_temp_grid is not None:
                # GFS grid is 721x1440 (same as wave grid), use same indices
                at_val = air_temp_grid[lat_idx, lon_idx]
                if not np.isnan(at_val):
                    air_temp = round(float(at_val), 1)

            feature = {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [round(lon, 2), round(lat, 2)]
                },
                "properties": {
                    "waveHeight": round1(wave_height),
                    "swells": swells,
                    "windWaves": wind_waves,
                    "wind": wind,
                    "airTemp": air_temp
                }
            }

            features.append(feature)

    # Create GeoJSON with metadata
    geojson = {
        "type": "FeatureCollection",
        "metadata": {
            "source": "WaveWatch III",
            "model_run": reference_time,
            "forecast_hour": forecast_hour,
            "valid_time": valid_time,
            "generated_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "grid_resolution": "6deg",
            "point_count": len(features)
        },
        "features": features
    }

    # Write output
    with open(output_path, 'w') as f:
        json.dump(geojson, f)

    return len(features), forecast_hour


def main():
    # Change to project directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    os.chdir(project_dir)

    # Find all GRIB files
    grib_pattern = os.path.join(GRIB_DIR, "gfswave.*.global.0p25.f*.grib2")
    grib_files = sorted(glob.glob(grib_pattern))

    if not grib_files:
        print(f"No GRIB files found matching: {grib_pattern}")
        return

    print(f"Found {len(grib_files)} GRIB files in {GRIB_DIR}/")
    print(f"Output directory: {OUTPUT_DIR}/")
    print("=" * 50)

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    total_features = 0
    f000_output = None
    failed_files = []

    # Extract model run date/cycle from first GRIB filename for GFS temp downloads
    # Filename format: gfswave.t{HH}z.global.0p25.f{FFF}.grib2
    first_filename = os.path.basename(grib_files[0])
    run_cycle_match = re.search(r'\.t(\d{2})z\.', first_filename)
    run_cycle = run_cycle_match.group(1) if run_cycle_match else "00"

    # Try to determine run date from GRIB metadata
    try:
        test_ds = cfgrib.open_datasets(grib_files[0])
        run_date = str(test_ds[0].time.values)[:10].replace("-", "")
    except Exception:
        run_date = datetime.utcnow().strftime("%Y%m%d")

    gfs_temp_dir = os.path.join("data", "gfs-temp")
    os.makedirs(gfs_temp_dir, exist_ok=True)

    print(f"\nGFS run: {run_date}/{run_cycle}z")
    print(f"Downloading GFS 2m temperature for each forecast hour...")

    # Process each file
    for i, grib_file in enumerate(grib_files, 1):
        forecast_hour = extract_forecast_hour(grib_file)
        output_file = os.path.join(OUTPUT_DIR, f"wave-data-f{forecast_hour:03d}.geojson")

        # Download GFS air temp for this forecast hour
        air_temp_grid = None
        temp_grib_path = download_gfs_temp_for_hour(run_date, run_cycle, forecast_hour, gfs_temp_dir)
        if temp_grib_path:
            air_temp_grid = load_gfs_air_temp(temp_grib_path)

        try:
            features_count, fhour = convert_grib_file(grib_file, output_file, i, len(grib_files), air_temp_grid)
            total_features += features_count

            # Track f000 for backward compatibility copy
            if forecast_hour == 0:
                f000_output = output_file
        except Exception as e:
            print(f"  WARNING: Failed to process {os.path.basename(grib_file)}: {e}")
            failed_files.append(os.path.basename(grib_file))
            continue

    # Create backward-compatible wave-data.geojson (copy of f000)
    if f000_output:
        legacy_output = os.path.join(OUTPUT_DIR, "wave-data.geojson")
        shutil.copy(f000_output, legacy_output)
        print(f"\nCreated {legacy_output} (copy of f000)")

    # Print summary
    succeeded = len(grib_files) - len(failed_files)
    print("\n" + "=" * 50)
    print("Conversion Complete!")
    print("=" * 50)
    print(f"Files processed:    {succeeded}/{len(grib_files)}")
    if succeeded > 0:
        print(f"Features per file:  ~{total_features // succeeded}")
    print(f"Total features:     {total_features}")
    print(f"Output directory:   {OUTPUT_DIR}/")

    # List output files
    print("\nGeoJSON files:")
    output_files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "wave-data*.geojson")))
    for f in output_files:
        size_kb = os.path.getsize(f) / 1024
        print(f"  {os.path.basename(f):30} {size_kb:6.1f} KB")

    # List PNG raster files
    png_files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "*.png")))
    if png_files:
        print(f"\nPNG raster files: {len(png_files)}")
        total_png_kb = sum(os.path.getsize(f) for f in png_files) / 1024
        print(f"  Total size: {total_png_kb:.0f} KB ({total_png_kb/1024:.1f} MB)")

    # Report failures
    if failed_files:
        print(f"\nWARNING: {len(failed_files)} file(s) failed to process:")
        for f in failed_files:
            print(f"    - {f}")

        success_rate = succeeded / len(grib_files)
        if success_rate < 0.9:
            print(f"\nError: Too many failures ({len(failed_files)}/{len(grib_files)})")
            sys.exit(1)
        else:
            print(f"\n{succeeded}/{len(grib_files)} files processed successfully")


if __name__ == "__main__":
    main()
